# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 829a64a03abc9e27e092cf8449cb0aea7f3e75d75174d1ad022d97d36c0e023d58da2e7ab4872b95397bb5cb46861841065c8384dee83a091c6d94384d2a866b

test:
  secret_key_base: ed174a92f2de84ddba6dd00ae8107f8d0c739a10042b358328169bba592eb2fef1933bda3eb3e446d8f4f718ca1ce87f6a713a73c361b35e4258f2d2a0c98123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
